baseURL = "/"
languageCode = "en-us"
title = "Digital Studies Resources" #"Digital Studies Resources"
themesDir = "themes"
theme = "dsr"


[[menu.main]]
    name = "Github"
    url = "https://github.com/bumatic/digital-studies-resources"
    weight = 1
    post = "_blank"

[[menu.content]]
    name = "Resources and Tools"
    url = "resources"
    weight = 1

[taxonomies]
  tag = "tags"


#theme = "hugo-whisper-theme"



#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = true
#pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30


    
#[markup]
#  [markup.tableOfContents]
#   startLevel = 2    
#    endLevel = -1
#    ordered = false
    

#[[menu.main]]
#    name = "Twitter"
#    url = "https://www.twitter.com/bumatic/"
#   weight = 2




[params]
  debug = false
  #logo = "/img/np_jar_1086705_FF11DD.svg"
  #google_analytics_id=""
  #homepage_button_link = '/resources'
  #homepage_button_text = 'Go to Resources'
  #homepage_intro = ''
  homepage_image = '/images/Digital-Studies-Resources-MindMap.svg'
  content_paths =  ["resources", "topics"]

  [params.homepage_meta_tags]
    meta_description = "Bootmatic.Bootmatic.Bootmatic.Bootmatic.Bootmatic.Bootmatic."
    meta_og_title = "Digital Studies Resources"
    meta_og_type = "Website"
    meta_og_url = "https://digital-studies.xyz"
    #meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    #meta_og_description = "Bootmatic.Bootmatic.Bootmatic.Bootmatic.Bootmatic.Bootmatic."
    #meta_twitter_card = "summary"
    #meta_twitter_site = "@bumatic"
    #meta_twitter_creator = "@bumatic"

  #[params.logo]
  #  mobile = "/img/np_jar_1086705_FF11DD.svg"
  #  standard  = "/img/np_jar_1086705_FF11DD.svg"



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4











