languageCode = "en-us"
title = "Digital Studies"

baseURL = "/"
themesDir = "themes"
theme = "hugo-whisper-theme"


pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/resources'
  homepage_button_text = 'Go to Resources'
  homepage_intro = ''
  #homepage_image = '/images/terminal.gif'

  # (Optional, default docs) Specify root page to render child pages as menu.
  # Page is resoled by .GetPage function: https://gohugo.io/functions/getpage/
  # For backward compatibility you can set '*' to render all sections to menu. Acts same as '/'
  Section = 'resources'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    #meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    #meta_og_title = "Hugo Whisper Theme"
    #meta_og_type = "website"
    #meta_og_url = "https://hugo-whisper.netlify.app"
    #meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    #meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@bumatic"
    meta_twitter_creator = "@bumatic"

  [params.logo]
      mobile = "/images/logo6.svg"
      standard  = "/images/logo6.svg"
