name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      #- name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        #run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.75.1"
          extended: true

      #- name: Change directory
      #  run: cd hugo

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        working-directory: ./hugo
        run: 
          #pwd
          #hugo version
          hugo --minify -b www.digital-studies.xyz

      - name: Deploy
        working-directory: ./hugo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: bumatic/digital-studies-xyz-live  
          publish_dir: ./public
          #   keep_files: true
          user_name: bumatic
          user_email: marcus.burkhardt@gmail.com
          publish_branch: master
        #   cname: example.com