name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      #- name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
      #  run: git submodule update --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.75.1"
          extended: true

      #- name: Change directory
      #  run: cd hugo

      - name: List Directory
        run: |
          cd hugo
          pwd

      - name: Built
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        #working-directory: ./hugo
        # -b https://www.digital-studies.xyz
        run: |
          pwd
          cd hugo
          hugo --debug
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        #working-directory: ./hugo
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: bumatic/digital-studies-xyz-live  
          publish_dir: ./hugo/public
          user_name: bumatic
          user_email: marcus.burkhardt@gmail.com
          publish_branch: master
        #   cname: example.com